/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyDslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class DockerfileElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Dockerfile");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cStatementsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cStatementsStatementParserRuleCall_0_0 = (RuleCall)cStatementsAssignment_0.eContents().get(0);
		private final RuleCall cNLTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//Dockerfile:
		//	(statements+=Statement NL)*;
		@Override public ParserRule getRule() { return rule; }
		
		//(statements+=Statement NL)*
		public Group getGroup() { return cGroup; }
		
		//statements+=Statement
		public Assignment getStatementsAssignment_0() { return cStatementsAssignment_0; }
		
		//Statement
		public RuleCall getStatementsStatementParserRuleCall_0_0() { return cStatementsStatementParserRuleCall_0_0; }
		
		//NL
		public RuleCall getNLTerminalRuleCall_1() { return cNLTerminalRuleCall_1; }
	}
	public class StatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Statement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cONBUILDKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final RuleCall cFromParserRuleCall_1_0 = (RuleCall)cAlternatives_1.eContents().get(0);
		private final RuleCall cCmdParserRuleCall_1_1 = (RuleCall)cAlternatives_1.eContents().get(1);
		private final RuleCall cEntrypointParserRuleCall_1_2 = (RuleCall)cAlternatives_1.eContents().get(2);
		private final RuleCall cVolumeParserRuleCall_1_3 = (RuleCall)cAlternatives_1.eContents().get(3);
		private final RuleCall cMaintainerParserRuleCall_1_4 = (RuleCall)cAlternatives_1.eContents().get(4);
		private final RuleCall cExposeParserRuleCall_1_5 = (RuleCall)cAlternatives_1.eContents().get(5);
		private final RuleCall cWorkdirParserRuleCall_1_6 = (RuleCall)cAlternatives_1.eContents().get(6);
		private final RuleCall cRunParserRuleCall_1_7 = (RuleCall)cAlternatives_1.eContents().get(7);
		private final RuleCall cEnvParserRuleCall_1_8 = (RuleCall)cAlternatives_1.eContents().get(8);
		private final RuleCall cLabelParserRuleCall_1_9 = (RuleCall)cAlternatives_1.eContents().get(9);
		private final RuleCall cAddParserRuleCall_1_10 = (RuleCall)cAlternatives_1.eContents().get(10);
		private final RuleCall cCopyParserRuleCall_1_11 = (RuleCall)cAlternatives_1.eContents().get(11);
		private final RuleCall cCOMMENTTerminalRuleCall_1_12 = (RuleCall)cAlternatives_1.eContents().get(12);
		
		//Statement:
		//	'ONBUILD '? (From | Cmd | Entrypoint | Volume | Maintainer | Expose | Workdir | Run | Env | Label | Add | Copy |
		//	COMMENT);
		@Override public ParserRule getRule() { return rule; }
		
		//'ONBUILD '? (From | Cmd | Entrypoint | Volume | Maintainer | Expose | Workdir | Run | Env | Label | Add | Copy |
		//COMMENT)
		public Group getGroup() { return cGroup; }
		
		//'ONBUILD '?
		public Keyword getONBUILDKeyword_0() { return cONBUILDKeyword_0; }
		
		//(From | Cmd | Entrypoint | Volume | Maintainer | Expose | Workdir | Run | Env | Label | Add | Copy | COMMENT)
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//From
		public RuleCall getFromParserRuleCall_1_0() { return cFromParserRuleCall_1_0; }
		
		//Cmd
		public RuleCall getCmdParserRuleCall_1_1() { return cCmdParserRuleCall_1_1; }
		
		//Entrypoint
		public RuleCall getEntrypointParserRuleCall_1_2() { return cEntrypointParserRuleCall_1_2; }
		
		//Volume
		public RuleCall getVolumeParserRuleCall_1_3() { return cVolumeParserRuleCall_1_3; }
		
		//Maintainer
		public RuleCall getMaintainerParserRuleCall_1_4() { return cMaintainerParserRuleCall_1_4; }
		
		//Expose
		public RuleCall getExposeParserRuleCall_1_5() { return cExposeParserRuleCall_1_5; }
		
		//Workdir
		public RuleCall getWorkdirParserRuleCall_1_6() { return cWorkdirParserRuleCall_1_6; }
		
		//Run
		public RuleCall getRunParserRuleCall_1_7() { return cRunParserRuleCall_1_7; }
		
		//Env
		public RuleCall getEnvParserRuleCall_1_8() { return cEnvParserRuleCall_1_8; }
		
		//Label
		public RuleCall getLabelParserRuleCall_1_9() { return cLabelParserRuleCall_1_9; }
		
		//Add
		public RuleCall getAddParserRuleCall_1_10() { return cAddParserRuleCall_1_10; }
		
		//Copy
		public RuleCall getCopyParserRuleCall_1_11() { return cCopyParserRuleCall_1_11; }
		
		//COMMENT
		public RuleCall getCOMMENTTerminalRuleCall_1_12() { return cCOMMENTTerminalRuleCall_1_12; }
	}
	public class FromElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.From");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFROMKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cPlatform_optionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPlatform_optionPLATFORM_OPTIONTerminalRuleCall_1_0 = (RuleCall)cPlatform_optionAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIMAGE_NAMEParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Assignment cTag_or_digestAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Alternatives cTag_or_digestAlternatives_3_0 = (Alternatives)cTag_or_digestAssignment_3.eContents().get(0);
		private final RuleCall cTag_or_digestIMAGE_TAGParserRuleCall_3_0_0 = (RuleCall)cTag_or_digestAlternatives_3_0.eContents().get(0);
		private final RuleCall cTag_or_digestIMAGE_DIGESTParserRuleCall_3_0_1 = (RuleCall)cTag_or_digestAlternatives_3_0.eContents().get(1);
		
		//From:
		//	'FROM ' platform_option=PLATFORM_OPTION? name=IMAGE_NAME tag_or_digest=(IMAGE_TAG | IMAGE_DIGEST)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'FROM ' platform_option=PLATFORM_OPTION? name=IMAGE_NAME tag_or_digest=(IMAGE_TAG | IMAGE_DIGEST)?
		public Group getGroup() { return cGroup; }
		
		//'FROM '
		public Keyword getFROMKeyword_0() { return cFROMKeyword_0; }
		
		//platform_option=PLATFORM_OPTION?
		public Assignment getPlatform_optionAssignment_1() { return cPlatform_optionAssignment_1; }
		
		//PLATFORM_OPTION
		public RuleCall getPlatform_optionPLATFORM_OPTIONTerminalRuleCall_1_0() { return cPlatform_optionPLATFORM_OPTIONTerminalRuleCall_1_0; }
		
		//name=IMAGE_NAME
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//IMAGE_NAME
		public RuleCall getNameIMAGE_NAMEParserRuleCall_2_0() { return cNameIMAGE_NAMEParserRuleCall_2_0; }
		
		//tag_or_digest=(IMAGE_TAG | IMAGE_DIGEST)?
		public Assignment getTag_or_digestAssignment_3() { return cTag_or_digestAssignment_3; }
		
		//(IMAGE_TAG | IMAGE_DIGEST)
		public Alternatives getTag_or_digestAlternatives_3_0() { return cTag_or_digestAlternatives_3_0; }
		
		//IMAGE_TAG
		public RuleCall getTag_or_digestIMAGE_TAGParserRuleCall_3_0_0() { return cTag_or_digestIMAGE_TAGParserRuleCall_3_0_0; }
		
		//IMAGE_DIGEST
		public RuleCall getTag_or_digestIMAGE_DIGESTParserRuleCall_3_0_1() { return cTag_or_digestIMAGE_DIGESTParserRuleCall_3_0_1; }
	}
	public class CmdElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Cmd");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCMDKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final RuleCall cEXEC_FORMParserRuleCall_1_0 = (RuleCall)cAlternatives_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cAlternatives_1.eContents().get(1);
		private final Action cCmdAction_1_1_0 = (Action)cGroup_1_1.eContents().get(0);
		private final RuleCall cSHELL_CMDTerminalRuleCall_1_1_1 = (RuleCall)cGroup_1_1.eContents().get(1);
		
		//Cmd:
		//	'CMD' (EXEC_FORM | {Cmd} SHELL_CMD);
		@Override public ParserRule getRule() { return rule; }
		
		//'CMD' (EXEC_FORM | {Cmd} SHELL_CMD)
		public Group getGroup() { return cGroup; }
		
		//'CMD'
		public Keyword getCMDKeyword_0() { return cCMDKeyword_0; }
		
		//(EXEC_FORM | {Cmd} SHELL_CMD)
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//EXEC_FORM
		public RuleCall getEXEC_FORMParserRuleCall_1_0() { return cEXEC_FORMParserRuleCall_1_0; }
		
		//{Cmd} SHELL_CMD
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//{Cmd}
		public Action getCmdAction_1_1_0() { return cCmdAction_1_1_0; }
		
		//SHELL_CMD
		public RuleCall getSHELL_CMDTerminalRuleCall_1_1_1() { return cSHELL_CMDTerminalRuleCall_1_1_1; }
	}
	public class RunElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Run");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRUNKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final RuleCall cEXEC_FORMParserRuleCall_1_0 = (RuleCall)cAlternatives_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cAlternatives_1.eContents().get(1);
		private final Action cRunAction_1_1_0 = (Action)cGroup_1_1.eContents().get(0);
		private final RuleCall cSHELL_CMDTerminalRuleCall_1_1_1 = (RuleCall)cGroup_1_1.eContents().get(1);
		
		//Run:
		//	'RUN' (EXEC_FORM | {Run} SHELL_CMD);
		@Override public ParserRule getRule() { return rule; }
		
		//'RUN' (EXEC_FORM | {Run} SHELL_CMD)
		public Group getGroup() { return cGroup; }
		
		//'RUN'
		public Keyword getRUNKeyword_0() { return cRUNKeyword_0; }
		
		//(EXEC_FORM | {Run} SHELL_CMD)
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//EXEC_FORM
		public RuleCall getEXEC_FORMParserRuleCall_1_0() { return cEXEC_FORMParserRuleCall_1_0; }
		
		//{Run} SHELL_CMD
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//{Run}
		public Action getRunAction_1_1_0() { return cRunAction_1_1_0; }
		
		//SHELL_CMD
		public RuleCall getSHELL_CMDTerminalRuleCall_1_1_1() { return cSHELL_CMDTerminalRuleCall_1_1_1; }
	}
	public class EntrypointElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Entrypoint");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cENTRYPOINTKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final RuleCall cEXEC_FORMParserRuleCall_1_0 = (RuleCall)cAlternatives_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cAlternatives_1.eContents().get(1);
		private final Action cEntrypointAction_1_1_0 = (Action)cGroup_1_1.eContents().get(0);
		private final RuleCall cSHELL_CMDTerminalRuleCall_1_1_1 = (RuleCall)cGroup_1_1.eContents().get(1);
		
		//Entrypoint:
		//	'ENTRYPOINT' (EXEC_FORM | {Entrypoint} SHELL_CMD);
		@Override public ParserRule getRule() { return rule; }
		
		//'ENTRYPOINT' (EXEC_FORM | {Entrypoint} SHELL_CMD)
		public Group getGroup() { return cGroup; }
		
		//'ENTRYPOINT'
		public Keyword getENTRYPOINTKeyword_0() { return cENTRYPOINTKeyword_0; }
		
		//(EXEC_FORM | {Entrypoint} SHELL_CMD)
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//EXEC_FORM
		public RuleCall getEXEC_FORMParserRuleCall_1_0() { return cEXEC_FORMParserRuleCall_1_0; }
		
		//{Entrypoint} SHELL_CMD
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//{Entrypoint}
		public Action getEntrypointAction_1_1_0() { return cEntrypointAction_1_1_0; }
		
		//SHELL_CMD
		public RuleCall getSHELL_CMDTerminalRuleCall_1_1_1() { return cSHELL_CMDTerminalRuleCall_1_1_1; }
	}
	public class VolumeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Volume");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVOLUMEKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final RuleCall cEXEC_FORMParserRuleCall_1_0 = (RuleCall)cAlternatives_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cAlternatives_1.eContents().get(1);
		private final Action cVolumeAction_1_1_0 = (Action)cGroup_1_1.eContents().get(0);
		private final RuleCall cSHELL_CMDTerminalRuleCall_1_1_1 = (RuleCall)cGroup_1_1.eContents().get(1);
		
		//Volume:
		//	'VOLUME' (EXEC_FORM | {Volume} SHELL_CMD);
		@Override public ParserRule getRule() { return rule; }
		
		//'VOLUME' (EXEC_FORM | {Volume} SHELL_CMD)
		public Group getGroup() { return cGroup; }
		
		//'VOLUME'
		public Keyword getVOLUMEKeyword_0() { return cVOLUMEKeyword_0; }
		
		//(EXEC_FORM | {Volume} SHELL_CMD)
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//EXEC_FORM
		public RuleCall getEXEC_FORMParserRuleCall_1_0() { return cEXEC_FORMParserRuleCall_1_0; }
		
		//{Volume} SHELL_CMD
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//{Volume}
		public Action getVolumeAction_1_1_0() { return cVolumeAction_1_1_0; }
		
		//SHELL_CMD
		public RuleCall getSHELL_CMDTerminalRuleCall_1_1_1() { return cSHELL_CMDTerminalRuleCall_1_1_1; }
	}
	public class MaintainerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Maintainer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMAINTAINERKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSHELL_CMDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Maintainer:
		//	'MAINTAINER' name=SHELL_CMD;
		@Override public ParserRule getRule() { return rule; }
		
		//'MAINTAINER' name=SHELL_CMD
		public Group getGroup() { return cGroup; }
		
		//'MAINTAINER'
		public Keyword getMAINTAINERKeyword_0() { return cMAINTAINERKeyword_0; }
		
		//name=SHELL_CMD
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//SHELL_CMD
		public RuleCall getNameSHELL_CMDTerminalRuleCall_1_0() { return cNameSHELL_CMDTerminalRuleCall_1_0; }
	}
	public class ExposeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Expose");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEXPOSEKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cPortsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPortsSHELL_CMDTerminalRuleCall_1_0 = (RuleCall)cPortsAssignment_1.eContents().get(0);
		
		//Expose:
		//	'EXPOSE' ports=SHELL_CMD;
		@Override public ParserRule getRule() { return rule; }
		
		//'EXPOSE' ports=SHELL_CMD
		public Group getGroup() { return cGroup; }
		
		//'EXPOSE'
		public Keyword getEXPOSEKeyword_0() { return cEXPOSEKeyword_0; }
		
		//ports=SHELL_CMD
		public Assignment getPortsAssignment_1() { return cPortsAssignment_1; }
		
		//SHELL_CMD
		public RuleCall getPortsSHELL_CMDTerminalRuleCall_1_0() { return cPortsSHELL_CMDTerminalRuleCall_1_0; }
	}
	public class WorkdirElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Workdir");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWORKDIRKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cPathAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPathSHELL_CMDTerminalRuleCall_1_0 = (RuleCall)cPathAssignment_1.eContents().get(0);
		
		//Workdir:
		//	'WORKDIR' path=SHELL_CMD;
		@Override public ParserRule getRule() { return rule; }
		
		//'WORKDIR' path=SHELL_CMD
		public Group getGroup() { return cGroup; }
		
		//'WORKDIR'
		public Keyword getWORKDIRKeyword_0() { return cWORKDIRKeyword_0; }
		
		//path=SHELL_CMD
		public Assignment getPathAssignment_1() { return cPathAssignment_1; }
		
		//SHELL_CMD
		public RuleCall getPathSHELL_CMDTerminalRuleCall_1_0() { return cPathSHELL_CMDTerminalRuleCall_1_0; }
	}
	public class EnvElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Env");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cENVKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cKey_value_pairsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cKey_value_pairsKV_PAIR_EQUALSTerminalRuleCall_1_0 = (RuleCall)cKey_value_pairsAssignment_1.eContents().get(0);
		
		//Env:
		//	'ENV ' key_value_pairs+=KV_PAIR_EQUALS+;
		@Override public ParserRule getRule() { return rule; }
		
		//'ENV ' key_value_pairs+=KV_PAIR_EQUALS+
		public Group getGroup() { return cGroup; }
		
		//'ENV '
		public Keyword getENVKeyword_0() { return cENVKeyword_0; }
		
		//key_value_pairs+=KV_PAIR_EQUALS+
		public Assignment getKey_value_pairsAssignment_1() { return cKey_value_pairsAssignment_1; }
		
		//KV_PAIR_EQUALS
		public RuleCall getKey_value_pairsKV_PAIR_EQUALSTerminalRuleCall_1_0() { return cKey_value_pairsKV_PAIR_EQUALSTerminalRuleCall_1_0; }
	}
	public class LabelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Label");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLABELKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cKey_value_pairsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cKey_value_pairsKV_PAIR_EQUALSTerminalRuleCall_1_0 = (RuleCall)cKey_value_pairsAssignment_1.eContents().get(0);
		
		//Label:
		//	'LABEL ' key_value_pairs+=KV_PAIR_EQUALS+;
		@Override public ParserRule getRule() { return rule; }
		
		//'LABEL ' key_value_pairs+=KV_PAIR_EQUALS+
		public Group getGroup() { return cGroup; }
		
		//'LABEL '
		public Keyword getLABELKeyword_0() { return cLABELKeyword_0; }
		
		//key_value_pairs+=KV_PAIR_EQUALS+
		public Assignment getKey_value_pairsAssignment_1() { return cKey_value_pairsAssignment_1; }
		
		//KV_PAIR_EQUALS
		public RuleCall getKey_value_pairsKV_PAIR_EQUALSTerminalRuleCall_1_0() { return cKey_value_pairsKV_PAIR_EQUALSTerminalRuleCall_1_0; }
	}
	public class AddElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Add");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cADDKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cChown_optionsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cChown_optionsCHOWN_OPTIONTerminalRuleCall_1_0 = (RuleCall)cChown_optionsAssignment_1.eContents().get(0);
		private final Assignment cFileAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cFileIDTerminalRuleCall_2_0 = (RuleCall)cFileAssignment_2.eContents().get(0);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Alternatives cAlternatives_3_0 = (Alternatives)cAlternatives_3.eContents().get(0);
		private final Keyword cQuestionMarkKeyword_3_0_0 = (Keyword)cAlternatives_3_0.eContents().get(0);
		private final Keyword cAsteriskKeyword_3_0_1 = (Keyword)cAlternatives_3_0.eContents().get(1);
		private final Group cGroup_3_1 = (Group)cAlternatives_3.eContents().get(1);
		private final Keyword cFullStopKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_3_1_1 = (RuleCall)cGroup_3_1.eContents().get(1);
		private final Assignment cDirectoryAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDirectorySHELL_CMDTerminalRuleCall_4_0 = (RuleCall)cDirectoryAssignment_4.eContents().get(0);
		
		//Add:
		//	'ADD ' chown_options=CHOWN_OPTION? file=ID (('?' | '*') | '.' ID)? directory=SHELL_CMD;
		@Override public ParserRule getRule() { return rule; }
		
		//'ADD ' chown_options=CHOWN_OPTION? file=ID (('?' | '*') | '.' ID)? directory=SHELL_CMD
		public Group getGroup() { return cGroup; }
		
		//'ADD '
		public Keyword getADDKeyword_0() { return cADDKeyword_0; }
		
		//chown_options=CHOWN_OPTION?
		public Assignment getChown_optionsAssignment_1() { return cChown_optionsAssignment_1; }
		
		//CHOWN_OPTION
		public RuleCall getChown_optionsCHOWN_OPTIONTerminalRuleCall_1_0() { return cChown_optionsCHOWN_OPTIONTerminalRuleCall_1_0; }
		
		//file=ID
		public Assignment getFileAssignment_2() { return cFileAssignment_2; }
		
		//ID
		public RuleCall getFileIDTerminalRuleCall_2_0() { return cFileIDTerminalRuleCall_2_0; }
		
		//(('?' | '*') | '.' ID)?
		public Alternatives getAlternatives_3() { return cAlternatives_3; }
		
		//('?' | '*')
		public Alternatives getAlternatives_3_0() { return cAlternatives_3_0; }
		
		//'?'
		public Keyword getQuestionMarkKeyword_3_0_0() { return cQuestionMarkKeyword_3_0_0; }
		
		//'*'
		public Keyword getAsteriskKeyword_3_0_1() { return cAsteriskKeyword_3_0_1; }
		
		//'.' ID
		public Group getGroup_3_1() { return cGroup_3_1; }
		
		//'.'
		public Keyword getFullStopKeyword_3_1_0() { return cFullStopKeyword_3_1_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_3_1_1() { return cIDTerminalRuleCall_3_1_1; }
		
		//directory=SHELL_CMD
		public Assignment getDirectoryAssignment_4() { return cDirectoryAssignment_4; }
		
		//SHELL_CMD
		public RuleCall getDirectorySHELL_CMDTerminalRuleCall_4_0() { return cDirectorySHELL_CMDTerminalRuleCall_4_0; }
	}
	public class CopyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Copy");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCOPYKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cChown_optionsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cChown_optionsCHOWN_OPTIONTerminalRuleCall_1_0 = (RuleCall)cChown_optionsAssignment_1.eContents().get(0);
		private final Assignment cFileAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cFileIDTerminalRuleCall_2_0 = (RuleCall)cFileAssignment_2.eContents().get(0);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Keyword cQuestionMarkKeyword_3_0 = (Keyword)cAlternatives_3.eContents().get(0);
		private final Keyword cAsteriskKeyword_3_1 = (Keyword)cAlternatives_3.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cFullStopKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_4_1 = (RuleCall)cGroup_4.eContents().get(1);
		private final Assignment cDirectoryAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cDirectorySHELL_CMDTerminalRuleCall_5_0 = (RuleCall)cDirectoryAssignment_5.eContents().get(0);
		
		//Copy:
		//	'COPY ' chown_options=CHOWN_OPTION? file=ID ('?' | '*')? ('.' ID)? directory=SHELL_CMD;
		@Override public ParserRule getRule() { return rule; }
		
		//'COPY ' chown_options=CHOWN_OPTION? file=ID ('?' | '*')? ('.' ID)? directory=SHELL_CMD
		public Group getGroup() { return cGroup; }
		
		//'COPY '
		public Keyword getCOPYKeyword_0() { return cCOPYKeyword_0; }
		
		//chown_options=CHOWN_OPTION?
		public Assignment getChown_optionsAssignment_1() { return cChown_optionsAssignment_1; }
		
		//CHOWN_OPTION
		public RuleCall getChown_optionsCHOWN_OPTIONTerminalRuleCall_1_0() { return cChown_optionsCHOWN_OPTIONTerminalRuleCall_1_0; }
		
		//file=ID
		public Assignment getFileAssignment_2() { return cFileAssignment_2; }
		
		//ID
		public RuleCall getFileIDTerminalRuleCall_2_0() { return cFileIDTerminalRuleCall_2_0; }
		
		//('?' | '*')?
		public Alternatives getAlternatives_3() { return cAlternatives_3; }
		
		//'?'
		public Keyword getQuestionMarkKeyword_3_0() { return cQuestionMarkKeyword_3_0; }
		
		//'*'
		public Keyword getAsteriskKeyword_3_1() { return cAsteriskKeyword_3_1; }
		
		//('.' ID)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'.'
		public Keyword getFullStopKeyword_4_0() { return cFullStopKeyword_4_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_4_1() { return cIDTerminalRuleCall_4_1; }
		
		//directory=SHELL_CMD
		public Assignment getDirectoryAssignment_5() { return cDirectoryAssignment_5; }
		
		//SHELL_CMD
		public RuleCall getDirectorySHELL_CMDTerminalRuleCall_5_0() { return cDirectorySHELL_CMDTerminalRuleCall_5_0; }
	}
	public class IMAGE_NAMEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.IMAGE_NAME");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cSolidusKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//IMAGE_NAME:
		//	ID ('/' ID)*;
		@Override public ParserRule getRule() { return rule; }
		
		//ID ('/' ID)*
		public Group getGroup() { return cGroup; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }
		
		//('/' ID)*
		public Group getGroup_1() { return cGroup_1; }
		
		//'/'
		public Keyword getSolidusKeyword_1_0() { return cSolidusKeyword_1_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	public class IMAGE_TAGElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.IMAGE_TAG");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cColonKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_1_0 = (RuleCall)cAlternatives_1.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1_1 = (RuleCall)cAlternatives_1.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_1_2 = (RuleCall)cAlternatives_1.eContents().get(2);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final RuleCall cIDTerminalRuleCall_2_0 = (RuleCall)cAlternatives_2.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_2_1 = (RuleCall)cAlternatives_2.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_2_2 = (RuleCall)cAlternatives_2.eContents().get(2);
		private final Keyword cHyphenMinusKeyword_2_3 = (Keyword)cAlternatives_2.eContents().get(3);
		private final Keyword cFullStopKeyword_2_4 = (Keyword)cAlternatives_2.eContents().get(4);
		
		//IMAGE_TAG:
		//	':' (ID | INT | STRING) (ID | INT | STRING | '-' | '.')*;
		@Override public ParserRule getRule() { return rule; }
		
		//':' (ID | INT | STRING) (ID | INT | STRING | '-' | '.')*
		public Group getGroup() { return cGroup; }
		
		//':'
		public Keyword getColonKeyword_0() { return cColonKeyword_0; }
		
		//(ID | INT | STRING)
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_0() { return cIDTerminalRuleCall_1_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1_1() { return cINTTerminalRuleCall_1_1; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_1_2() { return cSTRINGTerminalRuleCall_1_2; }
		
		//(ID | INT | STRING | '-' | '.')*
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_2_0() { return cIDTerminalRuleCall_2_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_2_1() { return cINTTerminalRuleCall_2_1; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_2_2() { return cSTRINGTerminalRuleCall_2_2; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_2_3() { return cHyphenMinusKeyword_2_3; }
		
		//'.'
		public Keyword getFullStopKeyword_2_4() { return cFullStopKeyword_2_4; }
	}
	public class IMAGE_DIGESTElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.IMAGE_DIGEST");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCommercialAtKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_1_0 = (RuleCall)cAlternatives_1.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1_1 = (RuleCall)cAlternatives_1.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_1_2 = (RuleCall)cAlternatives_1.eContents().get(2);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final RuleCall cIDTerminalRuleCall_2_0 = (RuleCall)cAlternatives_2.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_2_1 = (RuleCall)cAlternatives_2.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_2_2 = (RuleCall)cAlternatives_2.eContents().get(2);
		private final Keyword cHyphenMinusKeyword_2_3 = (Keyword)cAlternatives_2.eContents().get(3);
		private final Keyword cFullStopKeyword_2_4 = (Keyword)cAlternatives_2.eContents().get(4);
		
		//IMAGE_DIGEST:
		//	'@' (ID | INT | STRING) (ID | INT | STRING | '-' | '.')*;
		@Override public ParserRule getRule() { return rule; }
		
		//'@' (ID | INT | STRING) (ID | INT | STRING | '-' | '.')*
		public Group getGroup() { return cGroup; }
		
		//'@'
		public Keyword getCommercialAtKeyword_0() { return cCommercialAtKeyword_0; }
		
		//(ID | INT | STRING)
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_0() { return cIDTerminalRuleCall_1_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1_1() { return cINTTerminalRuleCall_1_1; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_1_2() { return cSTRINGTerminalRuleCall_1_2; }
		
		//(ID | INT | STRING | '-' | '.')*
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_2_0() { return cIDTerminalRuleCall_2_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_2_1() { return cINTTerminalRuleCall_2_1; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_2_2() { return cSTRINGTerminalRuleCall_2_2; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_2_3() { return cHyphenMinusKeyword_2_3; }
		
		//'.'
		public Keyword getFullStopKeyword_2_4() { return cFullStopKeyword_2_4; }
	}
	public class EXEC_FORMElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EXEC_FORM");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSpaceLeftSquareBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cExecutableAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cExecutableSTRINGTerminalRuleCall_1_0 = (RuleCall)cExecutableAssignment_1.eContents().get(0);
		private final Assignment cParametersAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cParametersEXEC_FORM_PARAMETERTerminalRuleCall_2_0 = (RuleCall)cParametersAssignment_2.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//EXEC_FORM:
		//	' [' executable=STRING parameters+=EXEC_FORM_PARAMETER* ']';
		@Override public ParserRule getRule() { return rule; }
		
		//' [' executable=STRING parameters+=EXEC_FORM_PARAMETER* ']'
		public Group getGroup() { return cGroup; }
		
		//' ['
		public Keyword getSpaceLeftSquareBracketKeyword_0() { return cSpaceLeftSquareBracketKeyword_0; }
		
		//executable=STRING
		public Assignment getExecutableAssignment_1() { return cExecutableAssignment_1; }
		
		//STRING
		public RuleCall getExecutableSTRINGTerminalRuleCall_1_0() { return cExecutableSTRINGTerminalRuleCall_1_0; }
		
		//parameters+=EXEC_FORM_PARAMETER*
		public Assignment getParametersAssignment_2() { return cParametersAssignment_2; }
		
		//EXEC_FORM_PARAMETER
		public RuleCall getParametersEXEC_FORM_PARAMETERTerminalRuleCall_2_0() { return cParametersEXEC_FORM_PARAMETERTerminalRuleCall_2_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_3() { return cRightSquareBracketKeyword_3; }
	}
	
	
	private final DockerfileElements pDockerfile;
	private final StatementElements pStatement;
	private final FromElements pFrom;
	private final CmdElements pCmd;
	private final RunElements pRun;
	private final EntrypointElements pEntrypoint;
	private final VolumeElements pVolume;
	private final MaintainerElements pMaintainer;
	private final ExposeElements pExpose;
	private final WorkdirElements pWorkdir;
	private final EnvElements pEnv;
	private final LabelElements pLabel;
	private final AddElements pAdd;
	private final CopyElements pCopy;
	private final IMAGE_NAMEElements pIMAGE_NAME;
	private final IMAGE_TAGElements pIMAGE_TAG;
	private final IMAGE_DIGESTElements pIMAGE_DIGEST;
	private final TerminalRule tPLATFORM_OPTION;
	private final TerminalRule tCHOWN_OPTION;
	private final EXEC_FORMElements pEXEC_FORM;
	private final TerminalRule tKV_PAIR_EQUALS;
	private final TerminalRule tID;
	private final TerminalRule tINT;
	private final TerminalRule tSTRING;
	private final TerminalRule tCONTINUE_NL;
	private final TerminalRule tNL;
	private final TerminalRule tANY_OTHER;
	private final TerminalRule tEXEC_FORM_PARAMETER;
	private final TerminalRule tSHELL_CMD;
	private final TerminalRule tCOMMENT;
	
	private final Grammar grammar;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.pDockerfile = new DockerfileElements();
		this.pStatement = new StatementElements();
		this.pFrom = new FromElements();
		this.pCmd = new CmdElements();
		this.pRun = new RunElements();
		this.pEntrypoint = new EntrypointElements();
		this.pVolume = new VolumeElements();
		this.pMaintainer = new MaintainerElements();
		this.pExpose = new ExposeElements();
		this.pWorkdir = new WorkdirElements();
		this.pEnv = new EnvElements();
		this.pLabel = new LabelElements();
		this.pAdd = new AddElements();
		this.pCopy = new CopyElements();
		this.pIMAGE_NAME = new IMAGE_NAMEElements();
		this.pIMAGE_TAG = new IMAGE_TAGElements();
		this.pIMAGE_DIGEST = new IMAGE_DIGESTElements();
		this.tPLATFORM_OPTION = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.PLATFORM_OPTION");
		this.tCHOWN_OPTION = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.CHOWN_OPTION");
		this.pEXEC_FORM = new EXEC_FORMElements();
		this.tKV_PAIR_EQUALS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.KV_PAIR_EQUALS");
		this.tID = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.ID");
		this.tINT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.INT");
		this.tSTRING = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.STRING");
		this.tCONTINUE_NL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.CONTINUE_NL");
		this.tNL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.NL");
		this.tANY_OTHER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.ANY_OTHER");
		this.tEXEC_FORM_PARAMETER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EXEC_FORM_PARAMETER");
		this.tSHELL_CMD = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.SHELL_CMD");
		this.tCOMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.COMMENT");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	
	//Dockerfile:
	//	(statements+=Statement NL)*;
	public DockerfileElements getDockerfileAccess() {
		return pDockerfile;
	}
	
	public ParserRule getDockerfileRule() {
		return getDockerfileAccess().getRule();
	}
	
	//Statement:
	//	'ONBUILD '? (From | Cmd | Entrypoint | Volume | Maintainer | Expose | Workdir | Run | Env | Label | Add | Copy |
	//	COMMENT);
	public StatementElements getStatementAccess() {
		return pStatement;
	}
	
	public ParserRule getStatementRule() {
		return getStatementAccess().getRule();
	}
	
	//From:
	//	'FROM ' platform_option=PLATFORM_OPTION? name=IMAGE_NAME tag_or_digest=(IMAGE_TAG | IMAGE_DIGEST)?;
	public FromElements getFromAccess() {
		return pFrom;
	}
	
	public ParserRule getFromRule() {
		return getFromAccess().getRule();
	}
	
	//Cmd:
	//	'CMD' (EXEC_FORM | {Cmd} SHELL_CMD);
	public CmdElements getCmdAccess() {
		return pCmd;
	}
	
	public ParserRule getCmdRule() {
		return getCmdAccess().getRule();
	}
	
	//Run:
	//	'RUN' (EXEC_FORM | {Run} SHELL_CMD);
	public RunElements getRunAccess() {
		return pRun;
	}
	
	public ParserRule getRunRule() {
		return getRunAccess().getRule();
	}
	
	//Entrypoint:
	//	'ENTRYPOINT' (EXEC_FORM | {Entrypoint} SHELL_CMD);
	public EntrypointElements getEntrypointAccess() {
		return pEntrypoint;
	}
	
	public ParserRule getEntrypointRule() {
		return getEntrypointAccess().getRule();
	}
	
	//Volume:
	//	'VOLUME' (EXEC_FORM | {Volume} SHELL_CMD);
	public VolumeElements getVolumeAccess() {
		return pVolume;
	}
	
	public ParserRule getVolumeRule() {
		return getVolumeAccess().getRule();
	}
	
	//Maintainer:
	//	'MAINTAINER' name=SHELL_CMD;
	public MaintainerElements getMaintainerAccess() {
		return pMaintainer;
	}
	
	public ParserRule getMaintainerRule() {
		return getMaintainerAccess().getRule();
	}
	
	//Expose:
	//	'EXPOSE' ports=SHELL_CMD;
	public ExposeElements getExposeAccess() {
		return pExpose;
	}
	
	public ParserRule getExposeRule() {
		return getExposeAccess().getRule();
	}
	
	//Workdir:
	//	'WORKDIR' path=SHELL_CMD;
	public WorkdirElements getWorkdirAccess() {
		return pWorkdir;
	}
	
	public ParserRule getWorkdirRule() {
		return getWorkdirAccess().getRule();
	}
	
	//Env:
	//	'ENV ' key_value_pairs+=KV_PAIR_EQUALS+;
	public EnvElements getEnvAccess() {
		return pEnv;
	}
	
	public ParserRule getEnvRule() {
		return getEnvAccess().getRule();
	}
	
	//Label:
	//	'LABEL ' key_value_pairs+=KV_PAIR_EQUALS+;
	public LabelElements getLabelAccess() {
		return pLabel;
	}
	
	public ParserRule getLabelRule() {
		return getLabelAccess().getRule();
	}
	
	//Add:
	//	'ADD ' chown_options=CHOWN_OPTION? file=ID (('?' | '*') | '.' ID)? directory=SHELL_CMD;
	public AddElements getAddAccess() {
		return pAdd;
	}
	
	public ParserRule getAddRule() {
		return getAddAccess().getRule();
	}
	
	//Copy:
	//	'COPY ' chown_options=CHOWN_OPTION? file=ID ('?' | '*')? ('.' ID)? directory=SHELL_CMD;
	public CopyElements getCopyAccess() {
		return pCopy;
	}
	
	public ParserRule getCopyRule() {
		return getCopyAccess().getRule();
	}
	
	//IMAGE_NAME:
	//	ID ('/' ID)*;
	public IMAGE_NAMEElements getIMAGE_NAMEAccess() {
		return pIMAGE_NAME;
	}
	
	public ParserRule getIMAGE_NAMERule() {
		return getIMAGE_NAMEAccess().getRule();
	}
	
	//IMAGE_TAG:
	//	':' (ID | INT | STRING) (ID | INT | STRING | '-' | '.')*;
	public IMAGE_TAGElements getIMAGE_TAGAccess() {
		return pIMAGE_TAG;
	}
	
	public ParserRule getIMAGE_TAGRule() {
		return getIMAGE_TAGAccess().getRule();
	}
	
	//IMAGE_DIGEST:
	//	'@' (ID | INT | STRING) (ID | INT | STRING | '-' | '.')*;
	public IMAGE_DIGESTElements getIMAGE_DIGESTAccess() {
		return pIMAGE_DIGEST;
	}
	
	public ParserRule getIMAGE_DIGESTRule() {
		return getIMAGE_DIGESTAccess().getRule();
	}
	
	//terminal PLATFORM_OPTION:
	//	'--platform=' (ID | INT) ':' ((ID | INT | STRING) (ID | INT | STRING | '-' | '.')*)? ' ';
	public TerminalRule getPLATFORM_OPTIONRule() {
		return tPLATFORM_OPTION;
	}
	
	//terminal CHOWN_OPTION:
	//	'--chown=' (ID | INT) ':' ((ID | INT | STRING) (ID | INT | STRING | '-' | '.')*)? ' ';
	public TerminalRule getCHOWN_OPTIONRule() {
		return tCHOWN_OPTION;
	}
	
	//EXEC_FORM:
	//	' [' executable=STRING parameters+=EXEC_FORM_PARAMETER* ']';
	public EXEC_FORMElements getEXEC_FORMAccess() {
		return pEXEC_FORM;
	}
	
	public ParserRule getEXEC_FORMRule() {
		return getEXEC_FORMAccess().getRule();
	}
	
	//terminal KV_PAIR_EQUALS:
	//	(ID | STRING) '=' (ID | STRING | INT) ' '?;
	public TerminalRule getKV_PAIR_EQUALSRule() {
		return tKV_PAIR_EQUALS;
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return tID;
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return tINT;
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return tSTRING;
	}
	
	//terminal CONTINUE_NL:
	//	'\\\n';
	public TerminalRule getCONTINUE_NLRule() {
		return tCONTINUE_NL;
	}
	
	//terminal NL:
	//	'\n'+;
	public TerminalRule getNLRule() {
		return tNL;
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return tANY_OTHER;
	}
	
	//terminal EXEC_FORM_PARAMETER:
	//	',' STRING;
	public TerminalRule getEXEC_FORM_PARAMETERRule() {
		return tEXEC_FORM_PARAMETER;
	}
	
	//terminal SHELL_CMD:
	//	(' ' | '\t') (!('\n' | '\r' | '\\') | '\\\n')*;
	public TerminalRule getSHELL_CMDRule() {
		return tSHELL_CMD;
	}
	
	//terminal COMMENT:
	//	'#' !('\n' | '\r')*;
	public TerminalRule getCOMMENTRule() {
		return tCOMMENT;
	}
}
