/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.dockerLang.ui.internal.DockerLangActivator;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DockerLangActivator.getInstance().getInjector("org.xtext.example.mydsl.MyDsl");
	}

}
