/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl.ui

import org.eclipse.ui.plugin.AbstractUIPlugin

/** 
 * Use this class to register components to be used within the Eclipse IDE.
 */
class MyDslUiModule extends AbstractMyDslUiModule {
	new(AbstractUIPlugin plugin) {
		super(plugin)
	}
}
