/**
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Copy</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Copy#getChown_options <em>Chown options</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Copy#getFile <em>File</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Copy#getDirectory <em>Directory</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCopy()
 * @model
 * @generated
 */
public interface Copy extends Statement
{
  /**
   * Returns the value of the '<em><b>Chown options</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Chown options</em>' attribute.
   * @see #setChown_options(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCopy_Chown_options()
   * @model
   * @generated
   */
  String getChown_options();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Copy#getChown_options <em>Chown options</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Chown options</em>' attribute.
   * @see #getChown_options()
   * @generated
   */
  void setChown_options(String value);

  /**
   * Returns the value of the '<em><b>File</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>File</em>' attribute.
   * @see #setFile(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCopy_File()
   * @model
   * @generated
   */
  String getFile();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Copy#getFile <em>File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>File</em>' attribute.
   * @see #getFile()
   * @generated
   */
  void setFile(String value);

  /**
   * Returns the value of the '<em><b>Directory</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Directory</em>' attribute.
   * @see #setDirectory(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCopy_Directory()
   * @model
   * @generated
   */
  String getDirectory();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Copy#getDirectory <em>Directory</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Directory</em>' attribute.
   * @see #getDirectory()
   * @generated
   */
  void setDirectory(String value);

} // Copy
