/**
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>From</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.From#getPlatform_option <em>Platform option</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.From#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.From#getTag_or_digest <em>Tag or digest</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFrom()
 * @model
 * @generated
 */
public interface From extends EObject
{
  /**
   * Returns the value of the '<em><b>Platform option</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Platform option</em>' attribute.
   * @see #setPlatform_option(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFrom_Platform_option()
   * @model
   * @generated
   */
  String getPlatform_option();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.From#getPlatform_option <em>Platform option</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Platform option</em>' attribute.
   * @see #getPlatform_option()
   * @generated
   */
  void setPlatform_option(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFrom_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.From#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Tag or digest</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tag or digest</em>' attribute.
   * @see #setTag_or_digest(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFrom_Tag_or_digest()
   * @model
   * @generated
   */
  String getTag_or_digest();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.From#getTag_or_digest <em>Tag or digest</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tag or digest</em>' attribute.
   * @see #getTag_or_digest()
   * @generated
   */
  void setTag_or_digest(String value);

} // From
