/**
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/DockerLang";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.DockerfileImpl <em>Dockerfile</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.DockerfileImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDockerfile()
   * @generated
   */
  int DOCKERFILE = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCKERFILE__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Dockerfile</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCKERFILE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.InstructionImpl <em>Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.InstructionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInstruction()
   * @generated
   */
  int INSTRUCTION = 1;

  /**
   * The feature id for the '<em><b>Statement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION__STATEMENT = 0;

  /**
   * The number of structural features of the '<em>Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.StatementImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 2;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__KEY = 0;

  /**
   * The feature id for the '<em><b>Platform option</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__PLATFORM_OPTION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__NAME = 2;

  /**
   * The feature id for the '<em><b>Tag or digest</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__TAG_OR_DIGEST = 3;

  /**
   * The feature id for the '<em><b>Exec form</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__EXEC_FORM = 4;

  /**
   * The feature id for the '<em><b>Shell form</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__SHELL_FORM = 5;

  /**
   * The feature id for the '<em><b>Ports</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__PORTS = 6;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__PATH = 7;

  /**
   * The feature id for the '<em><b>Key value pairs</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__KEY_VALUE_PAIRS = 8;

  /**
   * The feature id for the '<em><b>Chown options</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__CHOWN_OPTIONS = 9;

  /**
   * The feature id for the '<em><b>File</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__FILE = 10;

  /**
   * The feature id for the '<em><b>Directory</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__DIRECTORY = 11;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 12;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.EXEC_FORMImpl <em>EXEC FORM</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.EXEC_FORMImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getEXEC_FORM()
   * @generated
   */
  int EXEC_FORM = 3;

  /**
   * The feature id for the '<em><b>Executable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXEC_FORM__EXECUTABLE = 0;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXEC_FORM__PARAMETERS = 1;

  /**
   * The number of structural features of the '<em>EXEC FORM</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXEC_FORM_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Dockerfile <em>Dockerfile</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dockerfile</em>'.
   * @see org.xtext.example.mydsl.myDsl.Dockerfile
   * @generated
   */
  EClass getDockerfile();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Dockerfile#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see org.xtext.example.mydsl.myDsl.Dockerfile#getStatements()
   * @see #getDockerfile()
   * @generated
   */
  EReference getDockerfile_Statements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Instruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instruction</em>'.
   * @see org.xtext.example.mydsl.myDsl.Instruction
   * @generated
   */
  EClass getInstruction();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Instruction#getStatement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Statement</em>'.
   * @see org.xtext.example.mydsl.myDsl.Instruction#getStatement()
   * @see #getInstruction()
   * @generated
   */
  EReference getInstruction_Statement();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see org.xtext.example.mydsl.myDsl.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Statement#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.xtext.example.mydsl.myDsl.Statement#getKey()
   * @see #getStatement()
   * @generated
   */
  EAttribute getStatement_Key();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Statement#getPlatform_option <em>Platform option</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Platform option</em>'.
   * @see org.xtext.example.mydsl.myDsl.Statement#getPlatform_option()
   * @see #getStatement()
   * @generated
   */
  EAttribute getStatement_Platform_option();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Statement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Statement#getName()
   * @see #getStatement()
   * @generated
   */
  EAttribute getStatement_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Statement#getTag_or_digest <em>Tag or digest</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tag or digest</em>'.
   * @see org.xtext.example.mydsl.myDsl.Statement#getTag_or_digest()
   * @see #getStatement()
   * @generated
   */
  EAttribute getStatement_Tag_or_digest();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Statement#getExec_form <em>Exec form</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exec form</em>'.
   * @see org.xtext.example.mydsl.myDsl.Statement#getExec_form()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Exec_form();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Statement#getShell_form <em>Shell form</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Shell form</em>'.
   * @see org.xtext.example.mydsl.myDsl.Statement#getShell_form()
   * @see #getStatement()
   * @generated
   */
  EAttribute getStatement_Shell_form();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Statement#getPorts <em>Ports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ports</em>'.
   * @see org.xtext.example.mydsl.myDsl.Statement#getPorts()
   * @see #getStatement()
   * @generated
   */
  EAttribute getStatement_Ports();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Statement#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see org.xtext.example.mydsl.myDsl.Statement#getPath()
   * @see #getStatement()
   * @generated
   */
  EAttribute getStatement_Path();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.myDsl.Statement#getKey_value_pairs <em>Key value pairs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Key value pairs</em>'.
   * @see org.xtext.example.mydsl.myDsl.Statement#getKey_value_pairs()
   * @see #getStatement()
   * @generated
   */
  EAttribute getStatement_Key_value_pairs();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Statement#getChown_options <em>Chown options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Chown options</em>'.
   * @see org.xtext.example.mydsl.myDsl.Statement#getChown_options()
   * @see #getStatement()
   * @generated
   */
  EAttribute getStatement_Chown_options();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Statement#getFile <em>File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>File</em>'.
   * @see org.xtext.example.mydsl.myDsl.Statement#getFile()
   * @see #getStatement()
   * @generated
   */
  EAttribute getStatement_File();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Statement#getDirectory <em>Directory</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Directory</em>'.
   * @see org.xtext.example.mydsl.myDsl.Statement#getDirectory()
   * @see #getStatement()
   * @generated
   */
  EAttribute getStatement_Directory();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.EXEC_FORM <em>EXEC FORM</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EXEC FORM</em>'.
   * @see org.xtext.example.mydsl.myDsl.EXEC_FORM
   * @generated
   */
  EClass getEXEC_FORM();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.EXEC_FORM#getExecutable <em>Executable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Executable</em>'.
   * @see org.xtext.example.mydsl.myDsl.EXEC_FORM#getExecutable()
   * @see #getEXEC_FORM()
   * @generated
   */
  EAttribute getEXEC_FORM_Executable();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.myDsl.EXEC_FORM#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Parameters</em>'.
   * @see org.xtext.example.mydsl.myDsl.EXEC_FORM#getParameters()
   * @see #getEXEC_FORM()
   * @generated
   */
  EAttribute getEXEC_FORM_Parameters();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.DockerfileImpl <em>Dockerfile</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.DockerfileImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDockerfile()
     * @generated
     */
    EClass DOCKERFILE = eINSTANCE.getDockerfile();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOCKERFILE__STATEMENTS = eINSTANCE.getDockerfile_Statements();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.InstructionImpl <em>Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.InstructionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInstruction()
     * @generated
     */
    EClass INSTRUCTION = eINSTANCE.getInstruction();

    /**
     * The meta object literal for the '<em><b>Statement</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTRUCTION__STATEMENT = eINSTANCE.getInstruction_Statement();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.StatementImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATEMENT__KEY = eINSTANCE.getStatement_Key();

    /**
     * The meta object literal for the '<em><b>Platform option</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATEMENT__PLATFORM_OPTION = eINSTANCE.getStatement_Platform_option();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATEMENT__NAME = eINSTANCE.getStatement_Name();

    /**
     * The meta object literal for the '<em><b>Tag or digest</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATEMENT__TAG_OR_DIGEST = eINSTANCE.getStatement_Tag_or_digest();

    /**
     * The meta object literal for the '<em><b>Exec form</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__EXEC_FORM = eINSTANCE.getStatement_Exec_form();

    /**
     * The meta object literal for the '<em><b>Shell form</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATEMENT__SHELL_FORM = eINSTANCE.getStatement_Shell_form();

    /**
     * The meta object literal for the '<em><b>Ports</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATEMENT__PORTS = eINSTANCE.getStatement_Ports();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATEMENT__PATH = eINSTANCE.getStatement_Path();

    /**
     * The meta object literal for the '<em><b>Key value pairs</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATEMENT__KEY_VALUE_PAIRS = eINSTANCE.getStatement_Key_value_pairs();

    /**
     * The meta object literal for the '<em><b>Chown options</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATEMENT__CHOWN_OPTIONS = eINSTANCE.getStatement_Chown_options();

    /**
     * The meta object literal for the '<em><b>File</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATEMENT__FILE = eINSTANCE.getStatement_File();

    /**
     * The meta object literal for the '<em><b>Directory</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATEMENT__DIRECTORY = eINSTANCE.getStatement_Directory();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.EXEC_FORMImpl <em>EXEC FORM</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.EXEC_FORMImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getEXEC_FORM()
     * @generated
     */
    EClass EXEC_FORM = eINSTANCE.getEXEC_FORM();

    /**
     * The meta object literal for the '<em><b>Executable</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXEC_FORM__EXECUTABLE = eINSTANCE.getEXEC_FORM_Executable();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXEC_FORM__PARAMETERS = eINSTANCE.getEXEC_FORM_Parameters();

  }

} //MyDslPackage
