/**
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Volume</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getVolume()
 * @model
 * @generated
 */
public interface Volume extends Statement
{
} // Volume
