/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalDockerLanParser;
import org.xtext.example.mydsl.services.DockerLanGrammarAccess;

public class DockerLanParser extends AbstractAntlrParser {

	@Inject
	private DockerLanGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDockerLanParser createParser(XtextTokenStream stream) {
		return new InternalDockerLanParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public DockerLanGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DockerLanGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
