
package org.xtext.example.mydsl.validation
import org.eclipse.xtext.validation.Check
import org.xtext.example.mydsl.myDsl.Statement
import org.xtext.example.mydsl.myDsl.MyDslPackage
import org.xtext.example.mydsl.myDsl.Dockerfile
import org.eclipse.emf.common.util.EList
import org.eclipse.emf.ecore.EObject
import org.eclipse.emf.ecore.EReference

class MyDslValidatorXtend extends AbstractMyDslValidator {
	String tempString;
	EList statementList;
	String fromString;
	public static val INVALID_FIRST_STATEMENT = 'org.xtext.example.mydsl.INVALID_FIRST_STATEMENT';
	
	@Check 
	def checkFROM(Dockerfile tempFile, Statement statement){
		statementList = tempFile.statements;
		fromString = statementList.get(0).toString.substring(0,3);
		System.out.println(fromString);
		System.out.println("ha");
		InputOutput.<String>println("Hello World");
		
		if (!fromString.equals("FROM")){
			warning("The first statement should be a FROM command", MyDslPackage.Literals.DOCKERFILE__STATEMENTS, INVALID_FIRST_STATEMENT);
		}
		
	}
}

/*
 * generated by Xtext 2.20.0
 */

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */


